In [1]:
import pandas as pd
import json

In [2]:
def resetDict():
    # instantiate dictionary for dataframe
    games = dict()
    games["gameId"] = list()
    games["teamId"] = list()
    games["playerId"] = list()
    games["min"] = list()
    games["fgm"] = list()
    games["fga"] = list()
    games["ftm"] = list()
    games["fta"] = list()
    games["tpm"] = list()
    games["tpa"] = list()
    games["offReb"] = list()
    games["defReb"] = list()
    games["assists"] = list()
    games["steals"] = list()
    games["blocks"] = list()
    games["pFouls"] = list()
    games["turnovers"] = list()
    games["plusMinus"] = list()
#     print("resetDict")
    return games

def fillDataFrame(games, json_file):
    for raw_data in json_file:
        dat = raw_data["api"]["statistics"]
        for d in dat:
            games["gameId"].append(d["gameId"])
            games["teamId"].append(d["teamId"])
            games["playerId"].append(d["playerId"])
            games["min"].append(d["min"])
            games["fgm"].append(d["fgm"])
            games["fga"].append(d["fga"])
            games["ftm"].append(d["ftm"])
            games["fta"].append(d["fta"])
            games["tpm"].append(d["tpm"])
            games["tpa"].append(d["tpa"])
            games["offReb"].append(d["offReb"])
            games["defReb"].append(d["defReb"])
            games["assists"].append(d["assists"])
            games["steals"].append(d["steals"])
            games["blocks"].append(d["blocks"])
            games["pFouls"].append(d["pFouls"])
            games["turnovers"].append(d["turnovers"])
            games["plusMinus"].append(d["plusMinus"])
    
    df = pd.DataFrame(games)
#     print(df.dtypes)
    return df

def toIntMin(pStr):
    pStr = pStr.strip()
    if pStr == "":
        return 0
    elif len(pStr) < 1:
        return 0
    
    col_idx = pStr.find(":")
    ret = int(pStr[:col_idx])
    return ret

def toIntSec(pStr):
    pStr = pStr.strip()
    if pStr == "":
        return 0
    elif len(pStr) < 1:
        return 0
    
    col_idx = pStr.find(":")
    ret = int(pStr[col_idx+1:])
    return ret

def convertTodigit(digit, isInt=True):
    digit = digit.strip()
    if digit == "":
        return 0
    elif len(digit) < 1:
        return 0
    
    if isInt:
        return int(digit)
    else:
        return float(digit)

def convertDFdatatypes(df):
    df["minutes"] = df["min"].apply(toIntMin)
    df["seconds"] = df["min"].apply(toIntSec)
    df["fgm"] = df["fgm"].apply(convertTodigit)
    df["fga"] = df["fga"].apply(convertTodigit)
    df["ftm"] = df["ftm"].apply(convertTodigit)
    df["fta"] = df["fta"].apply(convertTodigit)
    df["tpm"] = df["tpm"].apply(convertTodigit)
    df["tpa"] = df["tpa"].apply(convertTodigit)
    df["offReb"] = df["offReb"].apply(convertTodigit)
    df["defReb"] = df["defReb"].apply(convertTodigit)
    df["assists"] = df["assists"].apply(convertTodigit)
    df["steals"] = df["steals"].apply(convertTodigit)
    df["blocks"] = df["blocks"].apply(convertTodigit)
    df["pFouls"] = df["pFouls"].apply(convertTodigit)
    df["turnovers"] = df["turnovers"].apply(convertTodigit)
    df["plusMinus"] = df["plusMinus"].apply(convertTodigit)
    
    return df

In [3]:
def process(file_name):
    with open(file_name) as json_file:
        data = json.load(json_file)
    
    games = resetDict()
    df = fillDataFrame(games, data)
    df = convertDFdatatypes(df)
    return df

In [4]:
df1 = process('../datasets/game_details.json')
df2 = process('../datasets/game_details_2.json')
df3 = process('../datasets/game_details_3.json')
df4 = process('../datasets/game_details_4.json')
df5 = process('../datasets/game_details_5.json')

In [5]:
# df.append(df2, ignore_index=True)
# df.append(df3, ignore_index=True)
# df.append(df4, ignore_index=True)
# df.append(df5, ignore_index=True)
frames = [df1, df2, df3, df4, df5]
df = pd.concat(frames)

In [7]:
print(df.shape)
df["gameId"].value_counts().sort_index()

(44514, 20)

4308    32
4309    39
4310    37
4311    40
4312    33
        ..
6217    26
6218    26
6219    26
6220    26
6221    26
Name: gameId, Length: 1381, dtype: int64

In [10]:
df[df['gameId'] == "6221"]

,gameId,teamId,playerId,min,fgm,fga,ftm,fta,tpm,tpa,offReb,defReb,assists,steals,blocks,pFouls,turnovers,plusMinus,minutes,seconds
1554,6221,38,314,41:05,7,16,7,8,1,5,1,5,3,2,1,4,2,-2,41,5
1555,6221,38,479,46:10,10,17,3,4,3,6,2,8,3,1,1,2,2,2,46,10
1556,6221,38,184,26:34,0,5,3,4,0,2,3,6,4,0,0,4,1,-7,26,34
1557,6221,38,203,17:43,0,0,0,0,0,0,0,1,3,1,0,1,1,7,17,43
1558,6221,38,327,41:42,9,16,4,6,4,7,2,5,10,3,0,5,3,16,41,42
1559,6221,38,732,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1560,6221,38,255,22:07,7,12,1,2,0,1,2,1,2,0,0,4,1,9,22,7
1561,6221,38,320,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1562,6221,38,345,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1563,6221,38,358,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1564,6221,38,837,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1565,6221,38,434,10:50,0,2,0,0,0,1,0,1,0,0,0,2,1,5,10,50
1566,6221,38,527,33:48,6,14,5,5,5,11,1,1,0,1,0,1,1,-10,33,48
1567,6221,11,256,32:01,9,15,1,5,3,6,0,2,2,0,1,3,1,-4,32,1
1568,6221,11,204,44:12,5,10,0,2,1,4,4,15,13,3,2,4,8,0,44,12
1569,6221,11,322,26:50,3,7,0,0,0,0,2,1,4,1,1,2,1,-4,26,50
1570,6221,11,514,31:59,8,12,10,10,4,6,1,4,0,2,0,3,2,5,31,59
1571,6221,11,124,41:53,6,17,6,6,3,11,1,2,7,2,1,3,3,-1,41,53
1572,6221,11,738,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1573,6221,11,61,2:50,0,1,0,0,0,0,0,1,0,0,0,0,0,-1,2,50
1574,6221,11,581,12:30,1,3,0,0,0,2,0,1,0,0,0,2,0,-16,12,30
1575,6221,11,117,18:44,4,9,4,7,0,1,1,4,2,0,1,3,0,-2,18,44
1576,6221,11,967,0:00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1577,6221,11,270,2:19,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,19
1578,6221,11,321,16:10,3,5,0,0,0,0,0,0,0,1,0,1,1,-2,16,10
1579,6221,11,835,10:29,0,1,0,0,0,1,2,1,0,0,0,2,0,4,10,29

In [12]:
df.to_csv('../datasets/gamedetails.csv')